language: python

python: "3.4"

sudo: false

env:
  - TOX_ENV=pytests
  - TOX_ENV=lint
  - TOX_ENV=coveralls

matrix:
  fast_finish: true

install:
  - pip install tox
  - (cd intersis_implementation;./bin/create-secret-settings.sh)

script:
  - tox -e $TOX_ENV